services:
  - type: web
    name: interview-question-generator
    env: python
    rootDir: prooo/flask_backend
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.12
      - key: PORT
        value: 9000
      - key: FRONTEND_URL
        sync: false
      - key: EXPRESS_URL
        sync: false 