services:
  - type: web
    name: interview-question-generator
    env: python
    buildCommand: cd flask_backend && pip install -r requirements.txt
    startCommand: cd flask_backend && gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.12
      - key: PORT
        value: 9000
      - key: FRONTEND_URL
        sync: false
      - key: EXPRESS_URL
        sync: false 